// Mock freelancer data — Bangladesh-based profiles

export const freelancers = [
  {
    id: 1,
    name: "Raihan Ahmed",
    skill: "Full-Stack Developer",
    category: "Development",
    rating: 4.9,
    reviews: 47,
    pricePerTask: 2500,
    currency: "BDT",
    avatar: null,
    initials: "RA",
    avatarColor: "#2563EB",
    location: "Dhaka",
    bio: "5 years building React & Node.js apps for startups. Specialized in fintech and e-commerce platforms.",
    tags: ["React", "Node.js", "PostgreSQL"],
    available: true,
    verified: true,
  },
  {
    id: 2,
    name: "Nadia Islam",
    skill: "UI/UX Designer",
    category: "Design",
    rating: 4.8,
    reviews: 63,
    pricePerTask: 1800,
    currency: "BDT",
    avatar: null,
    initials: "NI",
    avatarColor: "#7C3AED",
    location: "Chittagong",
    bio: "Product designer who has worked with 30+ startups across South Asia. Figma expert.",
    tags: ["Figma", "Prototyping", "Design Systems"],
    available: true,
    verified: true,
  },
  {
    id: 3,
    name: "Tanvir Hossain",
    skill: "SEO & Content",
    category: "Marketing",
    rating: 4.7,
    reviews: 29,
    pricePerTask: 800,
    currency: "BDT",
    avatar: null,
    initials: "TH",
    avatarColor: "#059669",
    location: "Sylhet",
    bio: "Helped 20+ Bangladeshi businesses rank on Google. Specializing in Bengali and English content.",
    tags: ["SEO", "Content Writing", "Analytics"],
    available: false,
    verified: true,
  },
  {
    id: 4,
    name: "Fatema Begum",
    skill: "Mobile Developer",
    category: "Development",
    rating: 4.9,
    reviews: 38,
    pricePerTask: 3200,
    currency: "BDT",
    avatar: null,
    initials: "FB",
    avatarColor: "#DC2626",
    location: "Dhaka",
    bio: "Flutter specialist building cross-platform apps. Published 8 apps on Play Store and App Store.",
    tags: ["Flutter", "Dart", "Firebase"],
    available: true,
    verified: true,
  },
  {
    id: 5,
    name: "Sazzad Karim",
    skill: "Data Analyst",
    category: "Data",
    rating: 4.6,
    reviews: 21,
    pricePerTask: 1500,
    currency: "BDT",
    avatar: null,
    initials: "SK",
    avatarColor: "#D97706",
    location: "Rajshahi",
    bio: "BUET graduate specializing in Python data pipelines and business intelligence dashboards.",
    tags: ["Python", "Power BI", "SQL"],
    available: true,
    verified: false,
  },
  {
    id: 6,
    name: "Meherun Nessa",
    skill: "Graphic Designer",
    category: "Design",
    rating: 4.8,
    reviews: 52,
    pricePerTask: 1200,
    currency: "BDT",
    avatar: null,
    initials: "MN",
    avatarColor: "#0891B2",
    location: "Comilla",
    bio: "Logo, brand identity, and print design. Worked with 50+ brands across retail, food, and fashion.",
    tags: ["Illustrator", "Photoshop", "Brand Design"],
    available: true,
    verified: true,
  },
];

export const categories = [
  "All",
  "Development",
  "Design",
  "Marketing",
  "Data",
];
