// Mock job listings — Bangladesh-focused roles

export const jobs = [
  {
    id: 1,
    title: "Build a bKash Payment Integration for E-Commerce Site",
    category: "Development",
    budget: { min: 5000, max: 8000 },
    currency: "BDT",
    duration: "1-2 weeks",
    postedBy: "Aarong Online",
    postedAt: "2 hours ago",
    description:
      "We need a developer to integrate bKash payment gateway into our existing Next.js e-commerce platform. Must have prior experience with bKash API.",
    tags: ["Next.js", "bKash API", "JavaScript"],
    applicants: 7,
    urgent: true,
    remote: true,
  },
  {
    id: 2,
    title: "Design Mobile UI for Ride-Sharing App (Figma)",
    category: "Design",
    budget: { min: 3000, max: 5000 },
    currency: "BDT",
    duration: "1 week",
    postedBy: "ShohorRide",
    postedAt: "5 hours ago",
    description:
      "Looking for a talented UI/UX designer to create a polished Figma prototype for our Dhaka-based ride-sharing startup. 12 screens required.",
    tags: ["Figma", "Mobile UI", "Prototyping"],
    applicants: 14,
    urgent: false,
    remote: true,
  },
  {
    id: 3,
    title: "Write Bengali & English Product Descriptions (50 items)",
    category: "Content",
    budget: { min: 1500, max: 2500 },
    currency: "BDT",
    duration: "3-5 days",
    postedBy: "Chaldal",
    postedAt: "1 day ago",
    description:
      "Need bilingual product descriptions for 50 grocery items. Must be fluent in both Bengali and English. SEO knowledge is a plus.",
    tags: ["Bengali Writing", "SEO", "Product Copy"],
    applicants: 23,
    urgent: false,
    remote: true,
  },
  {
    id: 4,
    title: "Build Flutter App for Local Delivery Service",
    category: "Development",
    budget: { min: 12000, max: 18000 },
    currency: "BDT",
    duration: "3-4 weeks",
    postedBy: "Paperfly BD",
    postedAt: "2 days ago",
    description:
      "Full Flutter app for iOS and Android. Features: live tracking, Nagad/bKash payment, order management. Please share previous app projects.",
    tags: ["Flutter", "Firebase", "Nagad API"],
    applicants: 9,
    urgent: false,
    remote: true,
  },
  {
    id: 5,
    title: "Monthly Social Media Management — Instagram & Facebook",
    category: "Marketing",
    budget: { min: 4000, max: 6000 },
    currency: "BDT",
    duration: "Ongoing",
    postedBy: "Meena Bazar",
    postedAt: "3 days ago",
    description:
      "Manage our social media presence across IG and FB. Create weekly posts, run engagement campaigns, and report monthly analytics. Must know Bangladeshi audience.",
    tags: ["Social Media", "Content Creation", "Analytics"],
    applicants: 31,
    urgent: false,
    remote: true,
  },
  {
    id: 6,
    title: "Data Dashboard in Power BI — Sales Analytics",
    category: "Data",
    budget: { min: 6000, max: 9000 },
    currency: "BDT",
    duration: "1-2 weeks",
    postedBy: "RoarBD",
    postedAt: "4 days ago",
    description:
      "Build an interactive Power BI dashboard connecting to our Google Sheets sales data. Must include revenue trends, product performance, and regional breakdown.",
    tags: ["Power BI", "Excel", "Data Visualization"],
    applicants: 12,
    urgent: true,
    remote: true,
  },
];

export const jobCategories = [
  "All",
  "Development",
  "Design",
  "Content",
  "Marketing",
  "Data",
];
